"""Static lookup tables and symbol normalization data used across the project."""

# ─── Exchange‑suffix + alias tables ───────────────────────────────────────────
STOCKS_SUFFIX: dict[str, str] = {  # updated 2026-04-11, event-driven
    "US": "",  # NYSE / Nasdaq
    "l": ".L",  # London
    "m": ".L",  # LSE
    "s": ".L",  # LSE
    "a": ".AS",  # Amsterdam
    "e": ".MC",  # MCE
    "p": ".PA",  # Paris
    "d": ".DE",  # Xetra
    "CA": ".TO",  # Toronto
    "ST": ".ST",  # Stockholm
    "BR": ".BR",  # Brussels
    "BE": ".BR",  # Euronext Brussels (Trading212 uses BE_, e.g. ABI_BE_EQ)
    "AS": ".AS",  # Amsterdam
    "MI": ".MI",  # Milan
    "SW": ".SW",  # Zurich
    "HK": ".HK",  # Hong‑Kong
    "VX": ".SW",  # Virt‑X (shares Zurich feed)
    "AT": ".VI",  # Vienna
    "1": ".SW",  # Swiss
    "U": ".L",  # LSE
}

# Maps the *core* symbol from Trading212 (before _US_EQ / exchange tag) → Yahoo ticker.
# Applied in convert_ticker() after stripping the T212 suffix, e.g. JEC_US_EQ → sym JEC → "J".
STOCKS_ALIASES: dict[str, str] = {  # updated 2026-08-01, event-driven
    "3LBA1": "3LBA",
    "AAXN": "AXON",
    "ABC": "COR",
    "AHAC": "HUMA",
    "AI1": "AI",
    "ANTM": "ELV",
    "ARNC": "HWM",
    "ASHTY": "SUNB",  # Ashtead ADR → Sunbelt Rentals Holdings, NYSE primary since Mar 2026
    "ASPI1": "ASPI",
    "BDEV": "BTRW",
    "BK": "BNY",  # BNY Mellon ticker rebrand on NYSE, May 2026
    "BMRG": "EOSE",
    "BRK/A": "BRK-A",
    "BRK_B": "BRK-B",
    "BT": "BT-A",
    "BYND1": "BYND",
    "CBG": "CBRE",
    "CCIR": "KYIV",
    "CCIV": "LCID",
    "CECE": "CECO",
    "CHKK": "EXE",
    "CLA": "OUST",  # Colonnade Acquisition SPAC → Ouster; T212 kept the pre-merger code
    "CNHI": "CNH",
    "DAI": "MBG",
    "DMYI": "IONQ",
    "DPS": "KDP",
    "EJFA": "PGY",
    "ECM": "RS1",  # Electrocomponents -> RS Group, renamed Mar 2022
    "FB": "META",
    "FLT": "CPAY",
    "FP": "TTE",
    "GARENA": "SE",
    "GNPK": "RDW",
    "GVC": "ENT",
    "GWAC": "CIFR",
    "HCN": "WELL",
    "HCP": "DOC",
    "HEICO": "HEI",  # T212 spells out the name; Yahoo quotes the NYSE ticker
    "HUTMF": "HUT",  # Hut 8 OTC line → Nasdaq HUT after US Bitcoin Corp merger
    "ICP": "ICG",
    "IIVI": "COHR",
    "IKNX": "WULF",
    "IPAX": "LUNR",
    "IPOB": "OPEN",
    "IPOE": "SOFI",
    "JEC": "J",
    "KCAC": "QS",
    "LOKB": "NVTS",
    "LSE": "LSEG",
    "MMC": "MRSH",
    "MYL": "VTRS",
    "NPA": "ASTS",
    "OAC": "HIMS",
    "PALAF1": "PALAF",
    "PCLN": "BKNG",
    "PKI": "RVTY",
    "RBS": "NWG",
    "RE": "EG",
    "RTP": "JOBY",
    "RTPY": "AUR",  # Reinvent Technology Partners Y SPAC → Aurora Innovation
    "SATS": "ECHO",  # EchoStar ticker rebrand on Nasdaq, Jun 2026; Yahoo froze SATS mid-Jul
    "SERV1": "SERV",  # Serve Robotics - stale T212 line, live Yahoo ticker is SERV
    "SFTW": "BKSY",
    "SL": "ABDN",
    "SNDK1": "SNDK",
    "SNE": "SONY",
    "SQ": "XYZ",
    "SRNG": "DNA",
    "SV": "SMR",  # NuScale Power - SPAC rename (Spring Valley → NuScale)
    "SVFC": "SYM",
    "SYMC": "GEN",
    "TLNE": "TLN",  # Talen Energy OTC line → Nasdaq TLN; Yahoo froze TLNE Jun 2026
    "TMK": "GL",
    "UTX": "RTX",
    "VACQ": "RKLB",
    "WLTW": "WTW",
    "WWE": "TKO",
    "XPOA": "QBTS",
    "YNDX": "NBIS",
    "FLY1": "FLY",
}


# Mixed membership (same set, two call sites):
# • Full T212 tickers (e.g. HYUDl_EQ) — convert_ticker() raises; fetch_holdings filters API rows.
# • Yahoo symbols (e.g. YNDX) — update_prices / backfill skip Instruments with that yahoo_symbol.
# Prefer STOCKS_ALIASES for simple renames so new syncs get a live Yahoo symbol; use this for
# halted shells, SPACs that no longer trade under the old symbol, or bad T212 lines to hide.
STOCKS_DELISTED: set[str] = {  # updated 2026-08-21, event-driven
    "11C.DE",  # 11 bit studios - Xetra line dead on Yahoo; primary 11B.WA is PLN (unsupported)
    "8GC.DE",  # legacy Xetra entry, no Yahoo price feed
    "AGR.L",  # Assura - delisted from LSE after PHP takeover, Oct 2025
    "DKI.DE",  # Daikin - Xetra line dead on Yahoo; primary 6367.T is JPY (unsupported)
    "FJK.DE",  # Fujikura - Xetra line dead on Yahoo; primary 5803.T is JPY (unsupported)
    "KEE.DE",  # Keyence - Xetra line dead on Yahoo; primary 6861.T is JPY (unsupported)
    "KGHA.DE",  # KGHM Polska Miedz - Xetra line dead on Yahoo; primary KGH.WA is PLN (unsupported)
    "PJXC.DE",  # Petrobras - Xetra line frozen on Yahoo (corrupt adj_close); primary PBR is the NYSE ADR
    "ALCC1",  # AltC Acquisition - merged into Oklo (OKLO)
    "BSAQ",  # Black Spade Acquisition - SPAC, no longer trading
    "CRH.L",  # CRH cancelled its LSE line Apr 2026; NYSE-only now (USD line is a separate instrument)
    "CTRA",  # Coterra Energy - merged into Devon Energy (DVN), May 2026
    "DEAC",  # Diamond Eagle Acquisition - merged into DraftKings (DKNG)
    "DMYQ",  # dMY Squared Technology - SPAC, no longer trading
    "EA",  # Electronic Arts - taken private by PIF/Silver Lake/Affinity, Aug 2026
    "HOLX",  # Hologic - taken private by Blackstone/TPG, Apr 2026
    "HYUDl_EQ",  # raw T212 code (rejected by convert_ticker, filtered in fetch_holdings)
    "MASI",  # Masimo - acquired by Danaher, Jun 2026
}

# Live tickers whose Wisesheets page currently has no PE block. Skipped by the nightly
# scrape but re-probed weekly (Sunday run), so coverage arriving — likely for recent
# IPOs — is picked up automatically; remove an entry once its probe starts succeeding.
# Also excluded from the pe_history_gaps audit while listed here.
WISESHEETS_NO_PE: set[str] = {  # updated 2026-07-22, auto re-probed weekly
    "SWMR",  # Swarmer - 2025 IPO, not yet covered by Wisesheets
}

SP500 = [  # updated 2026-08-21, review quarterly
    "MMM",
    "AOS",
    "ABT",
    "ABBV",
    "ACN",
    "ADBE",
    "AMD",
    "AES",
    "AFL",
    "A",
    "APD",
    "ABNB",
    "AKAM",
    "ALB",
    "ARE",
    "ALGN",
    "ALLE",
    "LNT",
    "ALL",
    "GOOGL",
    "GOOG",
    "MO",
    "AMZN",
    "AMCR",
    "AEE",
    "AEP",
    "AXP",
    "AIG",
    "AMT",
    "AWK",
    "AMP",
    "AME",
    "AMGN",
    "APH",
    "ADI",
    "AON",
    "APA",
    "APO",
    "AAPL",
    "AMAT",
    "APP",
    "APTV",
    "ACGL",
    "ADM",
    "ANET",
    "AJG",
    "AIZ",
    "T",
    "ATO",
    "ADSK",
    "ADP",
    "AZO",
    "AVB",
    "AVY",
    "AXON",
    "BKR",
    "BALL",
    "BAC",
    "BAX",
    "BDX",
    "BRK-B",
    "BBY",
    "TECH",
    "BIIB",
    "BLK",
    "BX",
    "XYZ",
    "BNY",
    "BA",
    "BKNG",
    "BSX",
    "BMY",
    "AVGO",
    "BR",
    "BRO",
    "BF-B",
    "BLDR",
    "BG",
    "BXP",
    "CHRW",
    "CDNS",
    "CPT",
    "COF",
    "CAH",
    "CCL",
    "CARR",
    "CAT",
    "CBOE",
    "CBRE",
    "CDW",
    "COR",
    "CNC",
    "CNP",
    "CF",
    "CRL",
    "SCHW",
    "CHTR",
    "CVX",
    "CVNA",
    "CMG",
    "CB",
    "CHD",
    "CIEN",
    "CI",
    "CINF",
    "CTAS",
    "CSCO",
    "C",
    "CFG",
    "CLX",
    "CME",
    "CMS",
    "KO",
    "CTSH",
    "COIN",
    "CL",
    "CMCSA",
    "COP",
    "ED",
    "STZ",
    "CEG",
    "COO",
    "CPRT",
    "GLW",
    "CPAY",
    "CTVA",
    "CSGP",
    "COST",
    "CRWD",
    "CCI",
    "CSX",
    "CMI",
    "CVS",
    "DHR",
    "DRI",
    "DDOG",
    "DVA",
    "DECK",
    "DE",
    "DELL",
    "DAL",
    "DVN",
    "DXCM",
    "FANG",
    "DLR",
    "DG",
    "DLTR",
    "D",
    "DPZ",
    "DASH",
    "DOV",
    "DOW",
    "DHI",
    "DTE",
    "DUK",
    "DD",
    "ETN",
    "EBAY",
    "ECL",
    "EIX",
    "EW",
    "FERG",
    "ELV",
    "EME",
    "EMR",
    "ETR",
    "EOG",
    "EQT",
    "EFX",
    "EQIX",
    "EQR",
    "ERIE",
    "ESS",
    "EL",
    "EG",
    "EVRG",
    "ES",
    "EXC",
    "EXE",
    "EXPE",
    "EXPD",
    "EXR",
    "XOM",
    "FFIV",
    "FDS",
    "FICO",
    "FAST",
    "FIX",
    "FRT",
    "FDX",
    "FIS",
    "FITB",
    "FSLR",
    "FE",
    "FISV",
    "F",
    "FTNT",
    "FTV",
    "FOXA",
    "FOX",
    "BEN",
    "FCX",
    "GRMN",
    "IT",
    "GE",
    "GEHC",
    "GEV",
    "GEN",
    "GNRC",
    "GD",
    "GIS",
    "GM",
    "GPC",
    "GILD",
    "GPN",
    "GL",
    "GDDY",
    "GS",
    "HAL",
    "HIG",
    "HAS",
    "HCA",
    "DOC",
    "HSIC",
    "HSY",
    "HPE",
    "HLT",
    "HD",
    "HON",
    "HRL",
    "HST",
    "HWM",
    "HPQ",
    "HUBB",
    "HUM",
    "HBAN",
    "HII",
    "IBM",
    "IEX",
    "IDXX",
    "ITW",
    "INCY",
    "IR",
    "PODD",
    "INTC",
    "IBKR",
    "ICE",
    "IFF",
    "IP",
    "INTU",
    "ISRG",
    "IVZ",
    "INVH",
    "IQV",
    "IRM",
    "JBHT",
    "JBL",
    "JKHY",
    "J",
    "JNJ",
    "JCI",
    "JPM",
    "KVUE",
    "KDP",
    "KEY",
    "KEYS",
    "KMB",
    "KIM",
    "KMI",
    "KKR",
    "KLAC",
    "KHC",
    "KR",
    "LHX",
    "LH",
    "LRCX",
    "LVS",
    "LDOS",
    "LEN",
    "LII",
    "LLY",
    "LIN",
    "LYV",
    "LMT",
    "L",
    "LOW",
    "LULU",
    "LYB",
    "MTB",
    "MPC",
    "MAR",
    "MRSH",
    "MLM",
    "MAS",
    "MA",
    "MKC",
    "MCD",
    "MCK",
    "MDT",
    "MRK",
    "META",
    "MET",
    "MTD",
    "MGM",
    "MCHP",
    "MU",
    "MSFT",
    "MAA",
    "MRNA",
    "TAP",
    "MDLZ",
    "MPWR",
    "MNST",
    "MCO",
    "MS",
    "MOS",
    "MSI",
    "MSCI",
    "NDAQ",
    "NTAP",
    "NFLX",
    "NEM",
    "NWSA",
    "NWS",
    "NEE",
    "NKE",
    "NI",
    "NDSN",
    "NSC",
    "NTRS",
    "NOC",
    "NCLH",
    "NRG",
    "NUE",
    "NVDA",
    "NVR",
    "NXPI",
    "ORLY",
    "OXY",
    "ODFL",
    "OMC",
    "ON",
    "OKE",
    "ORCL",
    "OTIS",
    "PCAR",
    "PKG",
    "PLTR",
    "PANW",
    "PSKY",
    "PH",
    "PAYX",
    "PYPL",
    "PNR",
    "PEP",
    "PFE",
    "PCG",
    "PM",
    "PSX",
    "PNW",
    "PNC",
    "PPG",
    "PPL",
    "PFG",
    "PG",
    "PGR",
    "PLD",
    "PRU",
    "PEG",
    "PTC",
    "PSA",
    "PHM",
    "PWR",
    "QCOM",
    "DGX",
    "Q",
    "RL",
    "RJF",
    "RTX",
    "O",
    "REG",
    "REGN",
    "RF",
    "RSG",
    "RMD",
    "RVTY",
    "HOOD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RCL",
    "SPGI",
    "CRM",
    "SBAC",
    "SLB",
    "STX",
    "SRE",
    "NOW",
    "SHW",
    "SPG",
    "SWKS",
    "SJM",
    "SW",
    "SNA",
    "SOLV",
    "SO",
    "LUV",
    "SWK",
    "SBUX",
    "STT",
    "STLD",
    "STE",
    "SYK",
    "SMCI",
    "SYF",
    "SNPS",
    "SYY",
    "TMUS",
    "TROW",
    "TTWO",
    "TPR",
    "TRGP",
    "TGT",
    "TEL",
    "TDY",
    "TER",
    "TSLA",
    "TXN",
    "TPL",
    "TXT",
    "TMO",
    "TJX",
    "TKO",
    "TTD",
    "TSCO",
    "TT",
    "TDG",
    "TRV",
    "TRMB",
    "TFC",
    "TYL",
    "TSN",
    "USB",
    "UBER",
    "UDR",
    "ULTA",
    "UNP",
    "UAL",
    "UPS",
    "URI",
    "UNH",
    "UHS",
    "VLO",
    "VTR",
    "VLTO",
    "VRSN",
    "VRSK",
    "VZ",
    "VRTX",
    "VTRS",
    "VICI",
    "V",
    "VST",
    "VMC",
    "WRB",
    "GWW",
    "WAB",
    "WMT",
    "DIS",
    "WBD",
    "WM",
    "WAT",
    "WEC",
    "WFC",
    "WELL",
    "WST",
    "WDC",
    "WY",
    "WSM",
    "WMB",
    "WTW",
    "WDAY",
    "WYNN",
    "XEL",
    "XYL",
    "YUM",
    "ZBRA",
    "ZBH",
    "ZTS",
    # 2025-26 index changes (synced against Wikipedia constituents, 2026-07-22);
    # includes spinoff listings FDXF (FedEx Freight) and HONA (Honeywell split)
    "ARES",
    "CASY",
    "COHR",
    "CRH",
    "ECHO",
    "FDXF",
    "FLEX",
    "HONA",
    "LITE",
    "MRVL",
    "SNDK",
    "VEEV",
    "VRT",
]

QQQ = [  # updated 2026-08-21, review quarterly
    "ADBE",
    "AMD",
    "ABNB",
    "ALNY",
    "GOOGL",
    "GOOG",
    "AMZN",
    "AEP",
    "AMGN",
    "ADI",
    "AAPL",
    "AMAT",
    "APP",
    "ARM",
    "ASML",
    "ADSK",
    "ADP",
    "AXON",
    "BKR",
    "BKNG",
    "AVGO",
    "CDNS",
    "CTAS",
    "CSCO",
    "CCEP",
    "CMCSA",
    "CEG",
    "CPRT",
    "COST",
    "CRWD",
    "CSX",
    "DDOG",
    "DXCM",
    "FANG",
    "DASH",
    "EXC",
    "FAST",
    "FER",
    "FTNT",
    "GEHC",
    "GILD",
    "HON",
    "IDXX",
    "INTC",
    "INTU",
    "ISRG",
    "KDP",
    "KLAC",
    "KHC",
    "LRCX",
    "LIN",
    "MAR",
    "MRVL",
    "MELI",
    "META",
    "MCHP",
    "MU",
    "MSFT",
    "MSTR",
    "MDLZ",
    "MPWR",
    "MNST",
    "NFLX",
    "NVDA",
    "NXPI",
    "ORLY",
    "ODFL",
    "PCAR",
    "PLTR",
    "PANW",
    "PAYX",
    "PYPL",
    "PDD",
    "PEP",
    "QCOM",
    "REGN",
    "ROP",
    "ROST",
    "STX",
    "SHOP",
    "SBUX",
    "SNPS",
    "TMUS",
    "TTWO",
    "TSLA",
    "TXN",
    "TRI",
    "VRTX",
    "WMT",
    "WBD",
    "WDC",
    "WDAY",
    "XEL",
    # 2025-26 reconstitution + fast-track adds (synced vs Wikipedia, 2026-07-22);
    # SPCX = SpaceX (Jun 2026 IPO, fast-tracked Jul 7 — index holds 103 listings)
    "ALAB",
    "CRWV",
    "HONA",
    "LITE",
    "NBIS",
    "RKLB",
    "SNDK",
    "SPCX",
    "TER",
]

FTSE_100 = [  # updated 2026-07-22, review quarterly
    "III.L",
    "ADM.L",
    "AAF.L",
    "ALW.L",
    "AAL.L",
    "ANTO.L",
    "ABF.L",
    "AZN.L",
    "AUTO.L",
    "AV.L",
    "BAB.L",
    "BA.L",
    "BARC.L",
    "BTRW.L",
    "BEZ.L",
    "BP.L",
    "BATS.L",
    "BLND.L",
    "BT-A.L",
    "BNZL.L",
    "BRBY.L",
    "CNA.L",
    "CCEP.L",
    "CCH.L",
    "CPG.L",
    "CTEC.L",
    "CRDA.L",
    "DCC.L",
    "DGE.L",
    "DPLM.L",
    "EDV.L",
    "ENT.L",
    "EXPN.L",
    "FCIT.L",
    "FRES.L",
    "GAW.L",
    "GLEN.L",
    "GSK.L",
    "HLN.L",
    "HLMA.L",
    "HSX.L",
    "HWDN.L",
    "HSBA.L",
    "ICG.L",
    "IGG.L",
    "IHG.L",
    "IMI.L",
    "IMB.L",
    "INF.L",
    "IAG.L",
    "ITRK.L",
    "JD.L",
    "BGEO.L",
    "KGF.L",
    "LAND.L",
    "LGEN.L",
    "LLOY.L",
    "LMP.L",
    "LSEG.L",
    "MNG.L",
    "MKS.L",
    "MRO.L",
    "MTLN.L",
    "NG.L",
    "NWG.L",
    "NXT.L",
    "PSON.L",
    "PSH.L",
    "PSN.L",
    "PCT.L",
    "PRU.L",
    "RKT.L",
    "REL.L",
    "RTO.L",
    "RIO.L",
    "RR.L",
    "SGE.L",
    "SBRY.L",
    "SDR.L",
    "SMT.L",
    "SGRO.L",
    "SVT.L",
    "SHEL.L",
    "SMIN.L",
    "SN.L",
    "SPX.L",
    "SSE.L",
    "STAN.L",
    "SDLF.L",
    "STJ.L",
    "TSCO.L",
    "BBOX.L",
    "ULVR.L",
    "UU.L",
    "VOD.L",
    "WEIR.L",
    "WTB.L",
    # 2025-26 promotions (synced vs Wikipedia, 2026-07-22)
    "ABDN.L",
    "CCC.L",
    "INVP.L",
]


# Physically-backed gold ETCs (SGLN=iShares, GLDW=WisdomTree, XAD5=Xtrackers), which Yahoo calls EQUITY.
# Fund for fees/screeners/earnings; NOT for cluster caps (one commodity, not a basket).
ETC_SYMBOLS = frozenset({"SGLN.L", "GLDW.L", "XAD5.DE"})  # updated 2026-08-23, event-driven

# Closed-end funds holding a portfolio of securities. Yahoo calls them EQUITY with
# no sector, so nothing in the payload separates them from an operating company.
INVESTMENT_TRUSTS = frozenset({"SMT.L", "FCIT.L", "UKW.L"})  # updated 2026-08-23, event-driven


# Where each ETF's holdings come from, for scripts/update_etf_holdings.py.
# Every held ETF has an issuer source; None would mean hand-maintained.
ETF_HOLDING_SOURCES = {  # updated 2026-08-21, review quarterly
    "XUTC.L": {
        "kind": "dws", "slug": "IE00BGQYRS42-msci-usa-information-technology-ucits-etf-1d",
        "index_name": "MSCI USA Information Technology 20-35 Custom Index",
        "source_note": "Xtrackers product-page API, ISIN-keyed",
    },
    "XNAS.L": {
        "kind": "dws", "slug": "IE00BMFKG444-nasdaq-100-ucits-etf-1c",
        "index_name": "Nasdaq 100",
        "source_note": "Xtrackers product-page API, ISIN-keyed",
    },
    "R1GR.L": {
        "kind": "ishares", "portfolio_id": "331965",
        "index_name": "Russell 1000 Growth UCITS 30/18 Capped",
        "source_note": "iShares portfolioId 331965",
    },
    "VUAG.L": {
        "kind": "sp500",
        "index_name": "S&P 500",
        "source_note": "Vanguard publishes no holdings file; cap-weighted from SP500",
        "caveat": "dual classes split by index ratio; 0.20pp mean error vs published weights",
    },
    "R2SC.L": {
        "kind": "ssga", "ticker": "zprr-gy",
        "index_name": "Russell 2000",
        "source_note": "SSGA daily holdings XLSX, ticker zprr-gy",
        "caveat": "only ~7% maps to tracked instruments — small caps are outside the universe",
    },
    "UKDV.L": {
        "kind": "ssga", "ticker": "spyg-gy",
        "index_name": "S&P UK Dividend Aristocrats",
        "source_note": "SSGA daily holdings XLSX, ticker spyg-gy",
    },
}


# ETF country and sector allocations — static snapshots that drift as funds rebalance.
# Update when a holding is added or when allocations look materially stale (typically quarterly).
# Universal lookup for any LSE-listed ETF: https://www.justetf.com/en/find-etf.html
# Per-fund provider pages are listed inline below.
ETF_COUNTRY_ALLOCATION = {  # updated 2026-05-04, review quarterly
    "XUTC.L": {  # Xtrackers MSCI USA Information Technology (Dist), isin: IE00BGQYRS42
        # https://etf.dws.com/en-gb/IE00BGQYRS42-msci-usa-information-technology-ucits-etf-1d/
        "United States": 99.29,
        "Netherlands": 0.35,
        "Ireland": 0.29,
        "Australia": 0.07,
    },
    "XNAS.L": {  # Xtrackers NASDAQ 100, isin: IE00BMFKG444
        # https://etf.dws.com/en-gb/IE00BMFKG444-nasdaq-100-ucits-etf-1c/
        "United States": 97.17,
        "Netherlands": 0.98,
        "Canada": 0.93,
        "United Kingdom": 0.35,
        "Ireland": 0.32,
        "Spain": 0.24,
        "Other": 0.01,
    },
    "R2SC.L": {  # SPDR Russell 2000 U.S. Small Cap (Acc), isin: IE00BJ38QD84
        # https://www.ssga.com/uk/en_gb/intermediary/etfs/state-street-spdr-russell-2000-us-small-cap-ucits-etf-acc-zprr-gy
        "United States": 99.28,
        "Canada": 0.42,
        "Brazil": 0.17,
        "Panama": 0.05,
        "Singapore": 0.04,
        "Israel": 0.02,
        "Norway": 0.01,
        "China": 0.01,
    },
    "UKDV.L": {  # SPDR S&P UK Dividend Aristocrats (Dist), isin: IE00B6S2Z822
        # https://www.ssga.com/uk/en_gb/intermediary/etfs/state-street-spdr-sp-uk-dividend-aristocrats-ucits-etf-dist-spyg-gy
        "United Kingdom": 100.00,
    },
    "VUAG.L": {  # Vanguard S&P 500 (Acc), isin: IE00BFMXXD54
        # https://www.vanguard.co.uk/professional/product/etf/equity/9694/sp-500-ucits-etf-usd-accumulating
        "United States": 100.00,
    },
    "R1GR.L": {  # iShares Russell 1000 Growth, isin: IE000NITTFF2
        # https://www.ishares.com/uk/individual/en/products/331965/
        "United States": 100.00,
    },
    "CIBR.L": {  # First Trust Nasdaq Cybersecurity (Acc), isin: IE00BF16M727
        # https://www.justetf.com/en/etf-profile.html?isin=IE00BF16M727
        "United States": 83.52,
        "Israel": 3.76,
        "Canada": 1.95,
        "Ireland": 1.86,
        "Japan": 1.28,
        "Netherlands": 1.16,
        "Other": 6.47,
    },
    "BOTZ.L": {  # Global X Robotics & Artificial Intelligence (Acc), isin: IE00BLCHJB90
        # https://globalxetfs.eu/funds/BOTZ
        "United States": 38.0,
        "Japan": 33.4,
        "Switzerland": 9.3,
        "China": 7.5,
        "South Korea": 5.1,
        "Hong Kong": 2.2,
        "United Kingdom": 1.4,
        "Norway": 1.3,
        "Canada": 0.9,
        "Finland": 0.9,
    },
}


# Same update cadence as ETF_COUNTRY_ALLOCATION — provider pages above apply here too.
ETF_SECTOR_ALLOCATION = {  # updated 2026-05-04, review quarterly
    "XUTC.L": {
        "Technology": 100.0,
    },
    "XNAS.L": {  # cap-weighted from constituents, Yahoo sectors, 2026-08-21
        "Technology": 57.08,
        "Communication Services": 16.05,
        "Consumer Cyclical": 12.91,
        "Industrials": 5.86,
        "Consumer Defensive": 4.2,
        "Healthcare": 2.28,
        "Utilities": 0.64,
        "Basic Materials": 0.55,
        "Energy": 0.3,
        "Financial Services": 0.13,
    },
    "R2SC.L": {
        "Industrials": 19.95,
        "Healthcare": 16.34,
        "Financial Services": 16.10,
        "Technology": 13.41,
        "Consumer Cyclical": 9.97,
        "Energy": 6.61,
        "Real Estate": 5.41,
        "Basic Materials": 4.50,
        "Utilities": 3.17,
        "Communication Services": 2.96,
        "Consumer Defensive": 1.53,
        "Other": 0.05,
    },
    "UKDV.L": {
        "Financial Services": 31.94,
        "Industrials": 23.08,
        "Consumer Defensive": 11.73,
        "Real Estate": 10.82,
        "Healthcare": 6.74,
        "Consumer Cyclical": 5.46,
        "Utilities": 4.53,
        "Basic Materials": 3.01,
        "Technology": 2.04,
        "Communication Services": 0.65,
    },
    "VUAG.L": {  # cap-weighted from constituents, Yahoo sectors, 2026-08-21
        "Technology": 36.1,
        "Financial Services": 12.54,
        "Communication Services": 10.42,
        "Consumer Cyclical": 10.15,
        "Healthcare": 9.4,
        "Industrials": 7.57,
        "Consumer Defensive": 5.03,
        "Energy": 3.43,
        "Utilities": 2.0,
        "Real Estate": 1.85,
        "Basic Materials": 1.51,
    },
    "R1GR.L": {
        "Technology": 52.17,
        "Consumer Cyclical": 13.13,
        "Communication Services": 12.91,
        "Healthcare": 6.60,
        "Industrials": 6.08,
        "Financial Services": 5.16,
        "Consumer Defensive": 2.50,
        "Real Estate": 0.40,
        "Energy": 0.37,
        "Basic Materials": 0.29,
        "Utilities": 0.25,
        "Other": 0.14,
    },
    "CIBR.L": {
        "Technology": 88.36,
        "Industrials": 3.01,
        "Communication Services": 2.16,
        "Other": 6.47,
    },
    "BOTZ.L": {
        "Technology": 43.3,
        "Industrials": 40.5,
        "Healthcare": 10.7,
        "Energy": 3.4,
        "Financial Services": 1.0,
        "Consumer Cyclical": 1.0,
        "Basic Materials": 0.1,
    },
}


# Quick ratio thresholds (warn, good) by sector — industry conventions, not hard rules.
QUICK_RATIO_THRESHOLDS = {  # updated 2025-10-02, static heuristic
    "Technology": (1.5, 2.5),
    "Industrials": (0.8, 1.2),
    "Healthcare": (1.3, 1.8),
    "Communication Services": (1.2, 1.8),
    "Consumer Cyclical": (0.8, 1.5),
    "Consumer Defensive": (0.8, 1.2),
    "Utilities": (0.5, 0.8),
    "Real Estate": (1, 1.5),
    "Basic Materials": (0.6, 1),
    "Energy": (0.6, 1),
    "Other": (1, 2),
}
