"""Static lookup tables and symbol normalization data used across the project."""

# ─── Exchange‑suffix + alias tables ───────────────────────────────────────────
STOCKS_SUFFIX: dict[str, str] = {
    "US": "",  # NYSE / Nasdaq
    "l": ".L",  # London
    "m": ".L",  # LSE
    "s": ".L",  # LSE
    "a": ".AS",  # Amsterdam
    "e": ".MC",  # MCE
    "p": ".PA",  # Paris
    "d": ".DE",  # Xetra
    "CA": ".TO",  # Toronto
    "ST": ".ST",  # Stockholm
    "BR": ".BR",  # Brussels
    "BE": ".BR",  # Euronext Brussels (Trading212 uses BE_, e.g. ABI_BE_EQ)
    "AS": ".AS",  # Amsterdam
    "MI": ".MI",  # Milan
    "SW": ".SW",  # Zurich
    "HK": ".HK",  # Hong‑Kong
    "VX": ".SW",  # Virt‑X (shares Zurich feed)
    "AT": ".VI",  # Vienna
    "1": ".SW",  # Swiss
    "U": ".L",  # LSE
}

# Maps the *core* symbol from Trading212 (before _US_EQ / exchange tag) → Yahoo ticker.
# Applied in convert_ticker() after stripping the T212 suffix, e.g. JEC_US_EQ → sym JEC → "J".
STOCKS_ALIASES: dict[str, str] = {
    "AAXN": "AXON",
    "ABC": "COR",
    "AHAC": "HUMA",
    "AI1": "AI",
    "ANTM": "ELV",
    "BHI": "BKR",
    "BRK/A": "BRK-A",
    "BRK_B": "BRK-B",
    "BYND1": "BYND",
    "CBG": "CBRE",
    "CCIR": "KYIV",
    "CCIV": "LCID",
    "CHKK": "EXE",
    "CNHI": "CNH",
    "DMYI": "IONQ",
    "DPS": "KDP",
    "EJFA": "PGY",
    "FB": "META",
    "FP": "TTE",
    "GARENA": "SE",
    "GNPK": "RDW",
    "HCN": "WELL",
    "HCP": "DOC",
    "IPAX": "LUNR",
    "IPOB": "OPEN",
    "IPOE": "SOFI",
    "JEC": "J",
    "KCAC": "QS",
    "LSE": "LSEG",
    "MYL": "VTRS",
    "NPA": "ASTS",
    "OAC": "HIMS",
    "PCLN": "BKNG",
    "PKI": "RVTY",
    "RBS": "NWG",
    "RTP": "JOBY",
    "SL": "ABDN",
    "SNE": "SONY",
    "SQ": "XYZ",
    "SRNG": "DNA",
    "SVFC": "SYM",
    "SYMC": "GEN",
    "TMK": "GL",
    "UTX": "RTX",
    "VACQ": "RKLB",
    "WLTW": "WTW",
    "WWE": "TKO",
    "XPOA": "QBTS",
    "YNDX": "NBIS",
}


# Mixed membership (same set, two call sites):
# • Full T212 tickers (e.g. HYUDl_EQ) — convert_ticker() raises; fetch_holdings filters API rows.
# • Yahoo symbols (e.g. YNDX) — update_prices / backfill skip Instruments with that yahoo_symbol.
# Prefer STOCKS_ALIASES for simple renames so new syncs get a live Yahoo symbol; use this for
# halted shells, SPACs that no longer trade under the old symbol, or bad T212 lines to hide.
STOCKS_DELISTED: set[str] = {
    "3LBA1.L",
    "8GC.DE",
    "AGR.L",
    "HYUDl_EQ",
}

SP500 = [
    "MMM",
    "AOS",
    "ABT",
    "ABBV",
    "ACN",
    "ADBE",
    "AMD",
    "AES",
    "AFL",
    "A",
    "APD",
    "ABNB",
    "AKAM",
    "ALB",
    "ARE",
    "ALGN",
    "ALLE",
    "LNT",
    "ALL",
    "GOOGL",
    "GOOG",
    "MO",
    "AMZN",
    "AMCR",
    "AEE",
    "AEP",
    "AXP",
    "AIG",
    "AMT",
    "AWK",
    "AMP",
    "AME",
    "AMGN",
    "APH",
    "ADI",
    "AON",
    "APA",
    "APO",
    "AAPL",
    "AMAT",
    "APP",
    "APTV",
    "ACGL",
    "ADM",
    "ANET",
    "AJG",
    "AIZ",
    "T",
    "ATO",
    "ADSK",
    "ADP",
    "AZO",
    "AVB",
    "AVY",
    "AXON",
    "BKR",
    "BALL",
    "BAC",
    "BAX",
    "BDX",
    "BRK-B",
    "BBY",
    "TECH",
    "BIIB",
    "BLK",
    "BX",
    "XYZ",
    "BK",
    "BA",
    "BKNG",
    "BSX",
    "BMY",
    "AVGO",
    "BR",
    "BRO",
    "BF-B",
    "BLDR",
    "BG",
    "BXP",
    "CHRW",
    "CDNS",
    "CPT",
    "CPB",
    "COF",
    "CAH",
    "CCL",
    "CARR",
    "CAT",
    "CBOE",
    "CBRE",
    "CDW",
    "COR",
    "CNC",
    "CNP",
    "CF",
    "CRL",
    "SCHW",
    "CHTR",
    "CVX",
    "CVNA",
    "CMG",
    "CB",
    "CHD",
    "CIEN",
    "CI",
    "CINF",
    "CTAS",
    "CSCO",
    "C",
    "CFG",
    "CLX",
    "CME",
    "CMS",
    "KO",
    "CTSH",
    "COIN",
    "CL",
    "CMCSA",
    "CAG",
    "COP",
    "ED",
    "STZ",
    "CEG",
    "COO",
    "CPRT",
    "GLW",
    "CPAY",
    "CRH",
    "CTVA",
    "CSGP",
    "COST",
    "CTRA",
    "CRWD",
    "CCI",
    "CSX",
    "CMI",
    "CVS",
    "DHR",
    "DRI",
    "DDOG",
    "DVA",
    "DECK",
    "DE",
    "DELL",
    "DAL",
    "DVN",
    "DXCM",
    "FANG",
    "DLR",
    "DG",
    "DLTR",
    "D",
    "DPZ",
    "DASH",
    "DOV",
    "DOW",
    "DHI",
    "DTE",
    "DUK",
    "DD",
    "ETN",
    "EBAY",
    "ECL",
    "EIX",
    "EW",
    "EA",
    "ELV",
    "EME",
    "EMR",
    "ETR",
    "EOG",
    "EPAM",
    "EQT",
    "EFX",
    "EQIX",
    "EQR",
    "ERIE",
    "ESS",
    "EL",
    "EG",
    "EVRG",
    "ES",
    "EXC",
    "EXE",
    "EXPE",
    "EXPD",
    "EXR",
    "XOM",
    "FFIV",
    "FDS",
    "FICO",
    "FAST",
    "FIX",
    "FRT",
    "FDX",
    "FIS",
    "FITB",
    "FSLR",
    "FE",
    "FISV",
    "F",
    "FTNT",
    "FTV",
    "FOXA",
    "FOX",
    "BEN",
    "FCX",
    "GRMN",
    "IT",
    "GE",
    "GEHC",
    "GEV",
    "GEN",
    "GNRC",
    "GD",
    "GIS",
    "GM",
    "GPC",
    "GILD",
    "GPN",
    "GL",
    "GDDY",
    "GS",
    "HAL",
    "HIG",
    "HAS",
    "HCA",
    "DOC",
    "HSIC",
    "HSY",
    "HPE",
    "HLT",
    "HOLX",
    "HD",
    "HON",
    "HRL",
    "HST",
    "HWM",
    "HPQ",
    "HUBB",
    "HUM",
    "HBAN",
    "HII",
    "IBM",
    "IEX",
    "IDXX",
    "ITW",
    "INCY",
    "IR",
    "PODD",
    "INTC",
    "IBKR",
    "ICE",
    "IFF",
    "IP",
    "IPG",
    "INTU",
    "ISRG",
    "IVZ",
    "INVH",
    "IQV",
    "IRM",
    "JBHT",
    "JBL",
    "JKHY",
    "J",
    "JNJ",
    "JCI",
    "JPM",
    "K",
    "KVUE",
    "KDP",
    "KEY",
    "KEYS",
    "KMB",
    "KIM",
    "KMI",
    "KKR",
    "KLAC",
    "KHC",
    "KR",
    "LHX",
    "LH",
    "LRCX",
    "LW",
    "LVS",
    "LDOS",
    "LEN",
    "LII",
    "LLY",
    "LIN",
    "LYV",
    "LMT",
    "L",
    "LOW",
    "LULU",
    "LYB",
    "MTB",
    "MPC",
    "MAR",
    "MMC",
    "MLM",
    "MAS",
    "MA",
    "MTCH",
    "MKC",
    "MCD",
    "MCK",
    "MDT",
    "MRK",
    "META",
    "MET",
    "MTD",
    "MGM",
    "MCHP",
    "MU",
    "MSFT",
    "MAA",
    "MRNA",
    "MOH",
    "TAP",
    "MDLZ",
    "MPWR",
    "MNST",
    "MCO",
    "MS",
    "MOS",
    "MSI",
    "MSCI",
    "NDAQ",
    "NTAP",
    "NFLX",
    "NEM",
    "NWSA",
    "NWS",
    "NEE",
    "NKE",
    "NI",
    "NDSN",
    "NSC",
    "NTRS",
    "NOC",
    "NCLH",
    "NRG",
    "NUE",
    "NVDA",
    "NVR",
    "NXPI",
    "ORLY",
    "OXY",
    "ODFL",
    "OMC",
    "ON",
    "OKE",
    "ORCL",
    "OTIS",
    "PCAR",
    "PKG",
    "PLTR",
    "PANW",
    "PSKY",
    "PH",
    "PAYX",
    "PAYC",
    "PYPL",
    "PNR",
    "PEP",
    "PFE",
    "PCG",
    "PM",
    "PSX",
    "PNW",
    "PNC",
    "POOL",
    "PPG",
    "PPL",
    "PFG",
    "PG",
    "PGR",
    "PLD",
    "PRU",
    "PEG",
    "PTC",
    "PSA",
    "PHM",
    "PWR",
    "QCOM",
    "DGX",
    "Q",
    "RL",
    "RJF",
    "RTX",
    "O",
    "REG",
    "REGN",
    "RF",
    "RSG",
    "RMD",
    "RVTY",
    "HOOD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RCL",
    "SPGI",
    "CRM",
    "SBAC",
    "SLB",
    "STX",
    "SRE",
    "NOW",
    "SHW",
    "SPG",
    "SWKS",
    "SJM",
    "SW",
    "SNA",
    "SOLV",
    "SO",
    "LUV",
    "SWK",
    "SBUX",
    "STT",
    "STLD",
    "STE",
    "SYK",
    "SMCI",
    "SYF",
    "SNPS",
    "SYY",
    "TMUS",
    "TROW",
    "TTWO",
    "TPR",
    "TRGP",
    "TGT",
    "TEL",
    "TDY",
    "TER",
    "TSLA",
    "TXN",
    "TPL",
    "TXT",
    "TMO",
    "TJX",
    "TKO",
    "TTD",
    "TSCO",
    "TT",
    "TDG",
    "TRV",
    "TRMB",
    "TFC",
    "TYL",
    "TSN",
    "USB",
    "UBER",
    "UDR",
    "ULTA",
    "UNP",
    "UAL",
    "UPS",
    "URI",
    "UNH",
    "UHS",
    "VLO",
    "VTR",
    "VLTO",
    "VRSN",
    "VRSK",
    "VZ",
    "VRTX",
    "VTRS",
    "VICI",
    "V",
    "VST",
    "VMC",
    "WRB",
    "GWW",
    "WAB",
    "WMT",
    "DIS",
    "WBD",
    "WM",
    "WAT",
    "WEC",
    "WFC",
    "WELL",
    "WST",
    "WDC",
    "WY",
    "WSM",
    "WMB",
    "WTW",
    "WDAY",
    "WYNN",
    "XEL",
    "XYL",
    "YUM",
    "ZBRA",
    "ZBH",
    "ZTS",
]


ETF_COUNTRY_ALLOCATION = {
    "XUTC.L": {  # Xtrackers MSCI USA IT
        "United States": 97.88,
        "Ireland": 1.40,
        "Netherlands": 0.34,
        "Australia": 0.20,
        "Singapore": 0.18,
    },
    "XNAS.L": {  # Xtrackers Nasdaq-100
        "United States": 95.00,
        "United Kingdom": 1.92,
        "Canada": 0.99,
        "Netherlands": 0.74,
        "Uruguay": 0.74,
        "Other": 0.61,
    },
    "R2SC.L": {  # SPDR Russell 2000 US Small Cap
        "United States": 94.75,
        "Bermuda": 0.84,
        "Cayman Islands": 0.65,
        "Canada": 0.57,
        "United Kingdom": 0.55,
        "Other": 2.64,
    },
    "UKDV.L": {  # SPDR UK Dividend Aristocrats
        "United Kingdom": 100.00,
    },
    "VUAG.L": {  # Vanguard S&P 500 (USD Acc)
        "United States": 97.48,
        "Ireland": 1.40,
        "United Kingdom": 0.55,
        "Switzerland": 0.26,
        "Netherlands": 0.11,
        "Other": 0.2,
    },
    "R1GR.L": {  # iShares Russell 1000 Growth
        "United States": 100.00,
    },
    "CIBR.L": {  # First Trust NASDAQ Cybersecurity
        "United States": 91.70,
        "Israel": 3.58,
        "Canada": 2.34,
        "Japan": 2.15,
        "United Kingdom": 0.22,
        "Other": 0.01,
    },
    "BOTZ.L": {  # Global X Robotics & AI UCITS
        "United States": 49.7,
        "Japan": 28.8,
        "Switzerland": 9.5,
        "China": 2.7,
        "Finland": 2.4,
        "South Korea": 2.0,
        "Hong Kong": 1.5,
        "Canada": 1.3,
        "United Kingdom": 1.2,
        "Norway": 0.9,
    },
    "CBRX.L": {
        "United States": 74.78,
        "Canada": 6.77,
        "Israel": 6.72,
        "South Korea": 3.18,
    },
}


ETF_SECTOR_ALLOCATION = {
    "XUTC.L": {
        "Technology": 100.0,
    },
    "XNAS.L": {
        "Technology": 51.16,
        "Communication Services": 16.05,
        "Consumer Cyclical": 13.21,
        "Consumer Defensive": 6.13,
        "Healthcare": 5.62,
        "Industrials": 3.75,
        "Utilities": 1.47,
        "Basic Materials": 1.46,
        "Energy": 0.50,
        "Financial Services": 0.44,
        "Real Estate": 0.21,
    },
    "R2SC.L": {
        "Financial Services": 18.06,
        "Healthcare": 16.96,
        "Industrials": 16.02,
        "Technology": 14.66,
        "Consumer Cyclical": 8.96,
        "Real Estate": 7.25,
        "Consumer Defensive": 4.41,
        "Energy": 4.41,
        "Basic Materials": 3.98,
        "Utilities": 3.17,
        "Communication Services": 2.10,
        "Other": 0.02,
    },
    "UKDV.L": {
        "Financial Services": 28.31,
        "Industrials": 16.15,
        "Consumer Defensive": 11.35,
        "Consumer Cyclical": 11.14,
        "Utilities": 10.85,
        "Healthcare": 7.45,
        "Real Estate": 4.86,
        "Communication Services": 4.47,
        "Technology": 3.75,
        "Basic Materials": 1.67,
    },
    "VUAG.L": {
        "Technology": 31.68,
        "Financial Services": 14.04,
        "Healthcare": 10.85,
        "Consumer Cyclical": 10.38,
        "Communication Services": 9.46,
        "Industrials": 7.66,
        "Consumer Defensive": 6.15,
        "Energy": 3.18,
        "Utilities": 2.56,
        "Real Estate": 2.25,
        "Basic Materials": 1.77,
        "Other": 0.02,
    },
    "R1GR.L": {
        "Technology": 48.75,
        "Consumer Cyclical": 14.28,
        "Communication Services": 13.48,
        "Healthcare": 7.59,
        "Financial Services": 6.85,
        "Consumer Defensive": 3.68,
        "Industrials": 3.51,
        "Basic Materials": 0.59,
        "Real Estate": 0.56,
        "Energy": 0.46,
        "Utilities": 0.24,
        "Other": 0.01,
    },
    "CIBR.L": {
        "Technology": 95.42,
        "Industrials": 4.58,
    },
    "BOTZ.L": {
        "Technology": 41.83,
        "Industrials": 41.81,
        "Healthcare": 12.76,
        "Financial Services": 2.10,
        "Consumer Cyclical": 1.07,
        "Energy": 0.43,
    },
    "CBRX.L": {
        "Technology": 93.49,
        "Communication Services": 4.97,
    },
}


QUICK_RATIO_THRESHOLDS = {
    "Technology": (1.5, 2.5),
    "Industrials": (0.8, 1.2),
    "Healthcare": (1.3, 1.8),
    "Communication Services": (1.2, 1.8),
    "Consumer Cyclical": (0.8, 1.5),
    "Consumer Defensive": (0.8, 1.2),
    "Utilities": (0.5, 0.8),
    "Real Estate": (1, 1.5),
    "Basic Materials": (0.6, 1),
    "Energy": (0.6, 1),
    "Other": (1, 2),
}
