"""Added MarketMetricsDaily model

Revision ID: 0b6078b92961
Revises: 75b5bd211ab1
Create Date: 2025-11-29 12:20:43.061009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b6078b92961"
down_revision: Union[str, Sequence[str], None] = "75b5bd211ab1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_metrics_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("buffett_indicator", sa.Float(), nullable=True),
        sa.Column("yield_spread", sa.Float(), nullable=True),
        sa.Column("fear_greed_index", sa.Float(), nullable=True),
        sa.Column("vix", sa.Float(), nullable=True),
        sa.Column("market_breadth_indicator", sa.Float(), nullable=True),
        sa.Column("sp500_above_sma200", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_market_metrics_daily_date"), "market_metrics_daily", ["date"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_metrics_daily_date"), table_name="market_metrics_daily")
    op.drop_table("market_metrics_daily")
    # ### end Alembic commands ###
