"""Add EarningsReport model

Revision ID: 16c286716a61
Revises: 72160884e7af
Create Date: 2026-01-09 11:19:31.667259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16c286716a61'
down_revision: Union[str, Sequence[str], None] = '72160884e7af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'date', name='uq_earnings_reports_instrument_date')
    )
    op.create_index('idx_earnings_reports_instrument_date', 'earnings_reports', ['instrument_id', 'date'], unique=False)
    op.create_index(op.f('ix_earnings_reports_instrument_id'), 'earnings_reports', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_reports_instrument_id'), table_name='earnings_reports')
    op.drop_index('idx_earnings_reports_instrument_date', table_name='earnings_reports')
    op.drop_table('earnings_reports')
    # ### end Alembic commands ###
