"""Add jensens_alpha, positions_total, positions_winning to PortfolioDaily model.

Revision ID: 1a5d3af83cb9
Revises: c6848bb774d0
Create Date: 2026-05-03 23:04:49.783948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5d3af83cb9'
down_revision: Union[str, Sequence[str], None] = 'c6848bb774d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_daily', sa.Column('jensens_alpha', sa.Float(), nullable=True))
    op.add_column('portfolio_daily', sa.Column('positions_total', sa.Integer(), nullable=True))
    op.add_column('portfolio_daily', sa.Column('positions_winning', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_daily', 'positions_winning')
    op.drop_column('portfolio_daily', 'positions_total')
    op.drop_column('portfolio_daily', 'jensens_alpha')
    # ### end Alembic commands ###
