"""Added F13 tables.

Revision ID: 492f9181dfd8
Revises: 16c286716a61
Create Date: 2026-02-27 21:02:10.089561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492f9181dfd8'
down_revision: Union[str, Sequence[str], None] = '16c286716a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form13f_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_table('form13f_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('accession_number', sa.String(length=30), nullable=False),
    sa.Column('total_value', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['form13f_managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'report_date', name='uq_form13f_manager_report_date')
    )
    op.create_index(op.f('ix_form13f_filings_manager_id'), 'form13f_filings', ['manager_id'], unique=False)
    op.create_index(op.f('ix_form13f_filings_report_date'), 'form13f_filings', ['report_date'], unique=False)
    op.create_table('form13f_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('title_of_class', sa.String(length=50), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['form13f_filings.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form13f_holding_cusip', 'form13f_holdings', ['cusip'], unique=False)
    op.create_index(op.f('ix_form13f_holdings_filing_id'), 'form13f_holdings', ['filing_id'], unique=False)
    op.create_index(op.f('ix_form13f_holdings_instrument_id'), 'form13f_holdings', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form13f_holdings_instrument_id'), table_name='form13f_holdings')
    op.drop_index(op.f('ix_form13f_holdings_filing_id'), table_name='form13f_holdings')
    op.drop_index('idx_form13f_holding_cusip', table_name='form13f_holdings')
    op.drop_table('form13f_holdings')
    op.drop_index(op.f('ix_form13f_filings_report_date'), table_name='form13f_filings')
    op.drop_index(op.f('ix_form13f_filings_manager_id'), table_name='form13f_filings')
    op.drop_table('form13f_filings')
    op.drop_table('form13f_managers')
    # ### end Alembic commands ###
