"""Add real_yield_10y and hy_oas to MarketMetricsDaily

Revision ID: 4c95414e08d1
Revises: 055ffc15718c
Create Date: 2026-05-29 19:07:56.871116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c95414e08d1'
down_revision: Union[str, Sequence[str], None] = '055ffc15718c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_metrics_daily', sa.Column('real_yield_10y', sa.Float(), nullable=True))
    op.add_column('market_metrics_daily', sa.Column('hy_oas', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_metrics_daily', 'hy_oas')
    op.drop_column('market_metrics_daily', 'real_yield_10y')
    # ### end Alembic commands ###
