"""Add PositionReview model

Revision ID: 5713db02e7c6
Revises: a7e21c40f9b3
Create Date: 2026-07-06 09:45:54.400207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5713db02e7c6'
down_revision: Union[str, Sequence[str], None] = 'a7e21c40f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_position_reviews_instrument_created', 'position_reviews', ['instrument_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_position_reviews_instrument_id'), 'position_reviews', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_reviews_instrument_id'), table_name='position_reviews')
    op.drop_index('idx_position_reviews_instrument_created', table_name='position_reviews')
    op.drop_table('position_reviews')
    # ### end Alembic commands ###
