"""Add balance_sheet and income_stmt JSONB columns to instruments_yahoo table

Revision ID: 6b4c056b6c8c
Revises: eb1c688ef73d
Create Date: 2026-04-27 14:41:11.167812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4c056b6c8c'
down_revision: Union[str, Sequence[str], None] = 'eb1c688ef73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments_yahoo', sa.Column('balance_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE instruments_yahoo SET balance_sheet = '{}' WHERE balance_sheet IS NULL")
    op.alter_column("instruments_yahoo", "balance_sheet", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)

    op.add_column('instruments_yahoo', sa.Column('income_stmt', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE instruments_yahoo SET income_stmt = '{}' WHERE income_stmt IS NULL")
    op.alter_column("instruments_yahoo", "income_stmt", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments_yahoo', 'income_stmt')
    op.drop_column('instruments_yahoo', 'balance_sheet')
    # ### end Alembic commands ###
