"""Add CIK to Instrument

Revision ID: 72160884e7af
Revises: 0b6078b92961
Create Date: 2025-12-08 19:17:00.882475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72160884e7af"
down_revision: Union[str, Sequence[str], None] = "0b6078b92961"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instruments", sa.Column("cik", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instruments", "cik")
    # ### end Alembic commands ###
