"""Initial migration

Revision ID: 75b5bd211ab1
Revises: 
Create Date: 2025-11-26 21:04:58.799500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75b5bd211ab1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_rates_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_currency_rates_date'), table_name='currency_rates_daily')
    op.create_index(op.f('ix_currency_rates_daily_date'), 'currency_rates_daily', ['date'], unique=False)
    op.alter_column('holdings_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_holdings_date'), table_name='holdings_daily')
    op.create_index('idx_holding_instrument_date', 'holdings_daily', ['instrument_id', 'date'], unique=False)
    op.create_index(op.f('ix_holdings_daily_date'), 'holdings_daily', ['date'], unique=False)
    op.alter_column('instruments', 'isin',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('instruments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('instruments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('uq_instruments_isin'), 'instruments', type_='unique')
    op.create_index(op.f('ix_instruments_isin'), 'instruments', ['isin'], unique=True)
    op.alter_column('instruments_yahoo', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('instruments_yahoo', 'analyst_price_targets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('instruments_yahoo', 'splits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.execute("UPDATE instruments_yahoo SET news = '[]' WHERE news IS NULL")
    op.alter_column('instruments_yahoo', 'news',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.execute("UPDATE instruments_yahoo SET pes = '{}' WHERE pes IS NULL")
    op.alter_column('instruments_yahoo', 'pes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('portfolio_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_portfolio_snapshots_date'), table_name='portfolio_daily')
    op.create_index(op.f('ix_portfolio_daily_date'), 'portfolio_daily', ['date'], unique=True)
    op.alter_column('prices_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_portfolio_daily_date'), table_name='portfolio_daily')
    op.create_index(op.f('ix_portfolio_snapshots_date'), 'portfolio_daily', ['date'], unique=True)
    op.alter_column('portfolio_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('instruments_yahoo', 'pes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('instruments_yahoo', 'news',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('instruments_yahoo', 'splits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('instruments_yahoo', 'analyst_price_targets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('instruments_yahoo', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_instruments_isin'), table_name='instruments')
    op.create_unique_constraint(op.f('uq_instruments_isin'), 'instruments', ['isin'], postgresql_nulls_not_distinct=False)
    op.alter_column('instruments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('instruments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('instruments', 'isin',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_index(op.f('ix_holdings_daily_date'), table_name='holdings_daily')
    op.drop_index('idx_holding_instrument_date', table_name='holdings_daily')
    op.create_index(op.f('ix_holdings_date'), 'holdings_daily', ['date'], unique=False)
    op.alter_column('holdings_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_currency_rates_daily_date'), table_name='currency_rates_daily')
    op.create_index(op.f('ix_currency_rates_date'), 'currency_rates_daily', ['date'], unique=False)
    op.alter_column('currency_rates_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
