"""Add insider trades 90d aggregates to instruments_metrics_daily

Revision ID: c6848bb774d0
Revises: 6b4c056b6c8c
Create Date: 2026-04-27 18:24:49.227612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6848bb774d0'
down_revision: Union[str, Sequence[str], None] = '6b4c056b6c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments_metrics_daily', sa.Column('insider_buy_count_90d', sa.Integer(), nullable=True))
    op.add_column('instruments_metrics_daily', sa.Column('insider_sell_count_90d', sa.Integer(), nullable=True))
    op.add_column('instruments_metrics_daily', sa.Column('insider_net_value_90d', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments_metrics_daily', 'insider_net_value_90d')
    op.drop_column('instruments_metrics_daily', 'insider_sell_count_90d')
    op.drop_column('instruments_metrics_daily', 'insider_buy_count_90d')
    # ### end Alembic commands ###
