"""Add thesis field to Instrument.

Revision ID: d3fc833b251e
Revises: 1a5d3af83cb9
Create Date: 2026-05-09 11:39:42.348369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3fc833b251e'
down_revision: Union[str, Sequence[str], None] = '1a5d3af83cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('thesis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'thesis')
    # ### end Alembic commands ###
