"""Add consumer_sentiment to market_metrics_daily

Revision ID: eb1c688ef73d
Revises: 492f9181dfd8
Create Date: 2026-03-05 19:12:49.125324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1c688ef73d'
down_revision: Union[str, Sequence[str], None] = '492f9181dfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_metrics_daily', sa.Column('consumer_sentiment', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_metrics_daily', 'consumer_sentiment')
    # ### end Alembic commands ###
